require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ForecastTodaysController do

  # This should return the minimal set of attributes required to create a valid
  # ForecastToday. As you add validations to ForecastToday, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { "date" => "2013-02-26" }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ForecastTodaysController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all forecast_todays as @forecast_todays" do
      forecast_today = ForecastToday.create! valid_attributes
      get :index, {}, valid_session
      assigns(:forecast_todays).should eq([forecast_today])
    end
  end

  describe "GET show" do
    it "assigns the requested forecast_today as @forecast_today" do
      forecast_today = ForecastToday.create! valid_attributes
      get :show, {:id => forecast_today.to_param}, valid_session
      assigns(:forecast_today).should eq(forecast_today)
    end
  end

  describe "GET new" do
    it "assigns a new forecast_today as @forecast_today" do
      get :new, {}, valid_session
      assigns(:forecast_today).should be_a_new(ForecastToday)
    end
  end

  describe "GET edit" do
    it "assigns the requested forecast_today as @forecast_today" do
      forecast_today = ForecastToday.create! valid_attributes
      get :edit, {:id => forecast_today.to_param}, valid_session
      assigns(:forecast_today).should eq(forecast_today)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new ForecastToday" do
        expect {
          post :create, {:forecast_today => valid_attributes}, valid_session
        }.to change(ForecastToday, :count).by(1)
      end

      it "assigns a newly created forecast_today as @forecast_today" do
        post :create, {:forecast_today => valid_attributes}, valid_session
        assigns(:forecast_today).should be_a(ForecastToday)
        assigns(:forecast_today).should be_persisted
      end

      it "redirects to the created forecast_today" do
        post :create, {:forecast_today => valid_attributes}, valid_session
        response.should redirect_to(ForecastToday.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved forecast_today as @forecast_today" do
        # Trigger the behavior that occurs when invalid params are submitted
        ForecastToday.any_instance.stub(:save).and_return(false)
        post :create, {:forecast_today => { "date" => "invalid value" }}, valid_session
        assigns(:forecast_today).should be_a_new(ForecastToday)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        ForecastToday.any_instance.stub(:save).and_return(false)
        post :create, {:forecast_today => { "date" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested forecast_today" do
        forecast_today = ForecastToday.create! valid_attributes
        # Assuming there are no other forecast_todays in the database, this
        # specifies that the ForecastToday created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        ForecastToday.any_instance.should_receive(:update_attributes).with({ "date" => "2013-02-26" })
        put :update, {:id => forecast_today.to_param, :forecast_today => { "date" => "2013-02-26" }}, valid_session
      end

      it "assigns the requested forecast_today as @forecast_today" do
        forecast_today = ForecastToday.create! valid_attributes
        put :update, {:id => forecast_today.to_param, :forecast_today => valid_attributes}, valid_session
        assigns(:forecast_today).should eq(forecast_today)
      end

      it "redirects to the forecast_today" do
        forecast_today = ForecastToday.create! valid_attributes
        put :update, {:id => forecast_today.to_param, :forecast_today => valid_attributes}, valid_session
        response.should redirect_to(forecast_today)
      end
    end

    describe "with invalid params" do
      it "assigns the forecast_today as @forecast_today" do
        forecast_today = ForecastToday.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ForecastToday.any_instance.stub(:save).and_return(false)
        put :update, {:id => forecast_today.to_param, :forecast_today => { "date" => "invalid value" }}, valid_session
        assigns(:forecast_today).should eq(forecast_today)
      end

      it "re-renders the 'edit' template" do
        forecast_today = ForecastToday.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ForecastToday.any_instance.stub(:save).and_return(false)
        put :update, {:id => forecast_today.to_param, :forecast_today => { "date" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested forecast_today" do
      forecast_today = ForecastToday.create! valid_attributes
      expect {
        delete :destroy, {:id => forecast_today.to_param}, valid_session
      }.to change(ForecastToday, :count).by(-1)
    end

    it "redirects to the forecast_todays list" do
      forecast_today = ForecastToday.create! valid_attributes
      delete :destroy, {:id => forecast_today.to_param}, valid_session
      response.should redirect_to(forecast_todays_url)
    end
  end

end
