require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe HoroscopesController do

  # This should return the minimal set of attributes required to create a valid
  # Horoscope. As you add validations to Horoscope, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { "sign" => "MyString" }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # HoroscopesController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all horoscopes as @horoscopes" do
      horoscope = Horoscope.create! valid_attributes
      get :index, {}, valid_session
      assigns(:horoscopes).should eq([horoscope])
    end
  end

  describe "GET show" do
    it "assigns the requested horoscope as @horoscope" do
      horoscope = Horoscope.create! valid_attributes
      get :show, {:id => horoscope.to_param}, valid_session
      assigns(:horoscope).should eq(horoscope)
    end
  end

  describe "GET new" do
    it "assigns a new horoscope as @horoscope" do
      get :new, {}, valid_session
      assigns(:horoscope).should be_a_new(Horoscope)
    end
  end

  describe "GET edit" do
    it "assigns the requested horoscope as @horoscope" do
      horoscope = Horoscope.create! valid_attributes
      get :edit, {:id => horoscope.to_param}, valid_session
      assigns(:horoscope).should eq(horoscope)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Horoscope" do
        expect {
          post :create, {:horoscope => valid_attributes}, valid_session
        }.to change(Horoscope, :count).by(1)
      end

      it "assigns a newly created horoscope as @horoscope" do
        post :create, {:horoscope => valid_attributes}, valid_session
        assigns(:horoscope).should be_a(Horoscope)
        assigns(:horoscope).should be_persisted
      end

      it "redirects to the created horoscope" do
        post :create, {:horoscope => valid_attributes}, valid_session
        response.should redirect_to(Horoscope.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved horoscope as @horoscope" do
        # Trigger the behavior that occurs when invalid params are submitted
        Horoscope.any_instance.stub(:save).and_return(false)
        post :create, {:horoscope => { "sign" => "invalid value" }}, valid_session
        assigns(:horoscope).should be_a_new(Horoscope)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Horoscope.any_instance.stub(:save).and_return(false)
        post :create, {:horoscope => { "sign" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested horoscope" do
        horoscope = Horoscope.create! valid_attributes
        # Assuming there are no other horoscopes in the database, this
        # specifies that the Horoscope created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Horoscope.any_instance.should_receive(:update_attributes).with({ "sign" => "MyString" })
        put :update, {:id => horoscope.to_param, :horoscope => { "sign" => "MyString" }}, valid_session
      end

      it "assigns the requested horoscope as @horoscope" do
        horoscope = Horoscope.create! valid_attributes
        put :update, {:id => horoscope.to_param, :horoscope => valid_attributes}, valid_session
        assigns(:horoscope).should eq(horoscope)
      end

      it "redirects to the horoscope" do
        horoscope = Horoscope.create! valid_attributes
        put :update, {:id => horoscope.to_param, :horoscope => valid_attributes}, valid_session
        response.should redirect_to(horoscope)
      end
    end

    describe "with invalid params" do
      it "assigns the horoscope as @horoscope" do
        horoscope = Horoscope.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Horoscope.any_instance.stub(:save).and_return(false)
        put :update, {:id => horoscope.to_param, :horoscope => { "sign" => "invalid value" }}, valid_session
        assigns(:horoscope).should eq(horoscope)
      end

      it "re-renders the 'edit' template" do
        horoscope = Horoscope.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Horoscope.any_instance.stub(:save).and_return(false)
        put :update, {:id => horoscope.to_param, :horoscope => { "sign" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested horoscope" do
      horoscope = Horoscope.create! valid_attributes
      expect {
        delete :destroy, {:id => horoscope.to_param}, valid_session
      }.to change(Horoscope, :count).by(-1)
    end

    it "redirects to the horoscopes list" do
      horoscope = Horoscope.create! valid_attributes
      delete :destroy, {:id => horoscope.to_param}, valid_session
      response.should redirect_to(horoscopes_url)
    end
  end

end
