require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe YktSessionsController do

  # This should return the minimal set of attributes required to create a valid
  # YktSession. As you add validations to YktSession, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { "date" => "2013-02-28" }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # YktSessionsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all ykt_sessions as @ykt_sessions" do
      ykt_session = YktSession.create! valid_attributes
      get :index, {}, valid_session
      assigns(:ykt_sessions).should eq([ykt_session])
    end
  end

  describe "GET show" do
    it "assigns the requested ykt_session as @ykt_session" do
      ykt_session = YktSession.create! valid_attributes
      get :show, {:id => ykt_session.to_param}, valid_session
      assigns(:ykt_session).should eq(ykt_session)
    end
  end

  describe "GET new" do
    it "assigns a new ykt_session as @ykt_session" do
      get :new, {}, valid_session
      assigns(:ykt_session).should be_a_new(YktSession)
    end
  end

  describe "GET edit" do
    it "assigns the requested ykt_session as @ykt_session" do
      ykt_session = YktSession.create! valid_attributes
      get :edit, {:id => ykt_session.to_param}, valid_session
      assigns(:ykt_session).should eq(ykt_session)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new YktSession" do
        expect {
          post :create, {:ykt_session => valid_attributes}, valid_session
        }.to change(YktSession, :count).by(1)
      end

      it "assigns a newly created ykt_session as @ykt_session" do
        post :create, {:ykt_session => valid_attributes}, valid_session
        assigns(:ykt_session).should be_a(YktSession)
        assigns(:ykt_session).should be_persisted
      end

      it "redirects to the created ykt_session" do
        post :create, {:ykt_session => valid_attributes}, valid_session
        response.should redirect_to(YktSession.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved ykt_session as @ykt_session" do
        # Trigger the behavior that occurs when invalid params are submitted
        YktSession.any_instance.stub(:save).and_return(false)
        post :create, {:ykt_session => { "date" => "invalid value" }}, valid_session
        assigns(:ykt_session).should be_a_new(YktSession)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        YktSession.any_instance.stub(:save).and_return(false)
        post :create, {:ykt_session => { "date" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested ykt_session" do
        ykt_session = YktSession.create! valid_attributes
        # Assuming there are no other ykt_sessions in the database, this
        # specifies that the YktSession created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        YktSession.any_instance.should_receive(:update_attributes).with({ "date" => "2013-02-28" })
        put :update, {:id => ykt_session.to_param, :ykt_session => { "date" => "2013-02-28" }}, valid_session
      end

      it "assigns the requested ykt_session as @ykt_session" do
        ykt_session = YktSession.create! valid_attributes
        put :update, {:id => ykt_session.to_param, :ykt_session => valid_attributes}, valid_session
        assigns(:ykt_session).should eq(ykt_session)
      end

      it "redirects to the ykt_session" do
        ykt_session = YktSession.create! valid_attributes
        put :update, {:id => ykt_session.to_param, :ykt_session => valid_attributes}, valid_session
        response.should redirect_to(ykt_session)
      end
    end

    describe "with invalid params" do
      it "assigns the ykt_session as @ykt_session" do
        ykt_session = YktSession.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        YktSession.any_instance.stub(:save).and_return(false)
        put :update, {:id => ykt_session.to_param, :ykt_session => { "date" => "invalid value" }}, valid_session
        assigns(:ykt_session).should eq(ykt_session)
      end

      it "re-renders the 'edit' template" do
        ykt_session = YktSession.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        YktSession.any_instance.stub(:save).and_return(false)
        put :update, {:id => ykt_session.to_param, :ykt_session => { "date" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested ykt_session" do
      ykt_session = YktSession.create! valid_attributes
      expect {
        delete :destroy, {:id => ykt_session.to_param}, valid_session
      }.to change(YktSession, :count).by(-1)
    end

    it "redirects to the ykt_sessions list" do
      ykt_session = YktSession.create! valid_attributes
      delete :destroy, {:id => ykt_session.to_param}, valid_session
      response.should redirect_to(ykt_sessions_url)
    end
  end

end
